import tkinter as tk
janela = tk.Tk()
janela.title("Estrutura base")
janela.geometry("500x300")
left_frame = tk.Frame(janela, bg="lightblue", width=100, height=300)
left_frame.place(relx=0, rely=0)
text_left_frame = tk.Label(left_frame, text="Frame Esquerdo", bg="lightblue")
text_left_frame.place(relx=0.05, rely=0.1)
top_right_frame = tk.Frame(janela, bg="lightgreen", width=400, height=260)
top_right_frame.place(relx=0.2, rely=0)
text_top_right_frame = tk.Label(top_right_frame, text="Frame Direito", bg="lightgreen")
text_top_right_frame.place(relx=0.1, rely=0.1)
bottom_right_frame = tk.Frame(janela, bg="yellow", width=400, height=60)
bottom_right_frame.place(relx=0.2, rely=0.80)
text_bottom_right_frame = tk.Label(bottom_right_frame, text="Frame Inferior Direito", bg="yellow")
text_bottom_right_frame.place(relx=0.1, rely=0.1)
janela.mainloop()