import tkinter as tk 
janela = tk.Tk()
janela.title("Estrutura do Formulário")
janela.geometry("500x300")
top_frame = tk.Frame(janela, bg="lightblue", width=450, height=50)
top_frame.place(relx=0.05, rely=0.05)
text_top_frame = tk.Label(top_frame, text="Frame superior", bg="lightblue", font=("Arial", 14))
text_top_frame.place(relx=0.35, rely=0.1)
middle_frame = tk.Frame(janela, bg="lightgreen", width=450, height=150)
middle_frame.place(relx=0.05, rely=0.25)
text_middle_frame = tk.Label(middle_frame, text="Frame do meio", bg="lightgreen", font=("Arial", 14))
text_middle_frame.place(relx=0.35, rely=0.45)
bottom_frame = tk.Frame(janela, bg="yellow", width=450, height=50)
bottom_frame.place(relx=0.05, rely=0.80)
text_bottom_frame = tk.Label(bottom_frame, text="Frame inferior", bg="yellow", font=("Arial", 14))
text_bottom_frame.place(relx=0.35, rely=0.1)
janela.mainloop()